server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    username: sa
    password:
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2-console
## Exception handling
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
